theme = "mizukitty"
hotreload_theme = true

# for debugging
# close_when_open = false
# as_window = true

[list]
max_entries = 5
placeholder = ">.<"

[search]
placeholder = "    ✧･ﾟ: *"

[activation_mode]
labels = "jkl;asdf"
