format = "$character"

right_format = "$all$time$sudo"
continuation_prompt = "»»"

[character]
success_symbol = "[ »»](bold green)"
error_symbol = "[ »»](bold red)"

# modules
[status]
disabled = true

[time]
disabled = false
time_format = "%I:%M %P"

[sudo]
disabled = false
format = "[$symbol]($style)"
symbol = "#"

# nerd fonts
[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[rust]
symbol = " "
